# Header
menu:
  Home: /
  Node Resource Search: http://www.tomatoframework.com
  Online Tools: http://tools.luaxlou.com
  简书: http://www.jianshu.com/users/874f1907d1a6/latest_articles
  Archives: /archives
  rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts


# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
